//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.09 at 02:10:13 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.uc3m.es/softlab/basu/event")
package es.uc3m.softlab.cbi4api.basu.mxml.event.publisher.xsd.basu.event;
