//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.14 at 04:16:29 PM BST 
//


package es.uc3m.softlab.cbi4api.basu.event.subscriber.xsd.basu.process;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the es.uc3m.softlab.cbi4api.basu.event.subscriber.xsd.basu.process package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Basu_QNAME = new QName("http://www.uc3m.es/softlab/basu/process", "basu");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: es.uc3m.softlab.cbi4api.basu.event.subscriber.xsd.basu.process
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Basu }
     * 
     */
    public Basu createBasu() {
        return new Basu();
    }

    /**
     * Create an instance of {@link CorrelationElement }
     * 
     */
    public CorrelationElement createCorrelationElement() {
        return new CorrelationElement();
    }

    /**
     * Create an instance of {@link CorrelationData }
     * 
     */
    public CorrelationData createCorrelationData() {
        return new CorrelationData();
    }

    /**
     * Create an instance of {@link ProcessInstance }
     * 
     */
    public ProcessInstance createProcessInstance() {
        return new ProcessInstance();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Basu }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.uc3m.es/softlab/basu/process", name = "basu")
    public JAXBElement<Basu> createBasu(Basu value) {
        return new JAXBElement<Basu>(_Basu_QNAME, Basu.class, null, value);
    }

}
