//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.07 at 10:34:52 PM IST 
//


package es.uc3m.softlab.cbi4api.basu.event.subscriber.xsd.basu.process;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import es.uc3m.softlab.cbi4api.basu.event.subscriber.xsd.TimeStampAdapter;


/**
 * <p>Java class for ProcessInstance complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProcessInstance">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="modelId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;choice>
 *           &lt;element name="correlationData" type="{http://www.uc3m.es/softlab/basu/process}CorrelationData"/>
 *           &lt;element name="processInstanceId" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN"/>
 *         &lt;/choice>
 *         &lt;element name="tstamp" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="state" type="{http://www.uc3m.es/softlab/basu/process}State" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProcessInstance", propOrder = {
    "modelId",
    "correlationData",
    "processInstanceId",
    "tstamp",
    "state"
})
public class ProcessInstance
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected String modelId;
    protected CorrelationData correlationData;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String processInstanceId;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(TimeStampAdapter.class)
    @XmlSchemaType(name = "dateTime")
    protected Calendar tstamp;
    @XmlList
    protected List<String> state;

    /**
     * Gets the value of the modelId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModelId() {
        return modelId;
    }

    /**
     * Sets the value of the modelId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModelId(String value) {
        this.modelId = value;
    }

    public boolean isSetModelId() {
        return (this.modelId!= null);
    }

    /**
     * Gets the value of the correlationData property.
     * 
     * @return
     *     possible object is
     *     {@link CorrelationData }
     *     
     */
    public CorrelationData getCorrelationData() {
        return correlationData;
    }

    /**
     * Sets the value of the correlationData property.
     * 
     * @param value
     *     allowed object is
     *     {@link CorrelationData }
     *     
     */
    public void setCorrelationData(CorrelationData value) {
        this.correlationData = value;
    }

    public boolean isSetCorrelationData() {
        return (this.correlationData!= null);
    }

    /**
     * Gets the value of the processInstanceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessInstanceId() {
        return processInstanceId;
    }

    /**
     * Sets the value of the processInstanceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessInstanceId(String value) {
        this.processInstanceId = value;
    }

    public boolean isSetProcessInstanceId() {
        return (this.processInstanceId!= null);
    }

    /**
     * Gets the value of the tstamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Calendar getTstamp() {
        return tstamp;
    }

    /**
     * Sets the value of the tstamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTstamp(Calendar value) {
        this.tstamp = value;
    }

    public boolean isSetTstamp() {
        return (this.tstamp!= null);
    }

    /**
     * Gets the value of the state property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the state property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getState().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getState() {
        if (state == null) {
            state = new ArrayList<String>();
        }
        return this.state;
    }

    public boolean isSetState() {
        return ((this.state!= null)&&(!this.state.isEmpty()));
    }

    public void unsetState() {
        this.state = null;
    }

}
