//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.09 at 03:34:43 PM BST 
//


package es.uc3m.softlab.cbi4api.basu.xes.event.publisher.xsd.xes;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the es.uc3m.softlab.cbi4api.basu.xes.event.publisher.xsd.xes package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Log_QNAME = new QName("http://www.xes-standard.org/", "log");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: es.uc3m.softlab.cbi4api.basu.xes.event.publisher.xsd.xes
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AttributeBooleanType }
     * 
     */
    public AttributeBooleanType createAttributeBooleanType() {
        return new AttributeBooleanType();
    }

    /**
     * Create an instance of {@link GlobalsType }
     * 
     */
    public GlobalsType createGlobalsType() {
        return new GlobalsType();
    }

    /**
     * Create an instance of {@link TraceType }
     * 
     */
    public TraceType createTraceType() {
        return new TraceType();
    }

    /**
     * Create an instance of {@link AttributeIntType }
     * 
     */
    public AttributeIntType createAttributeIntType() {
        return new AttributeIntType();
    }

    /**
     * Create an instance of {@link AttributeFloatType }
     * 
     */
    public AttributeFloatType createAttributeFloatType() {
        return new AttributeFloatType();
    }

    /**
     * Create an instance of {@link ExtensionType }
     * 
     */
    public ExtensionType createExtensionType() {
        return new ExtensionType();
    }

    /**
     * Create an instance of {@link EventType }
     * 
     */
    public EventType createEventType() {
        return new EventType();
    }

    /**
     * Create an instance of {@link AttributeDateType }
     * 
     */
    public AttributeDateType createAttributeDateType() {
        return new AttributeDateType();
    }

    /**
     * Create an instance of {@link AttributeStringType }
     * 
     */
    public AttributeStringType createAttributeStringType() {
        return new AttributeStringType();
    }

    /**
     * Create an instance of {@link LogType }
     * 
     */
    public LogType createLogType() {
        return new LogType();
    }

    /**
     * Create an instance of {@link ClassifierType }
     * 
     */
    public ClassifierType createClassifierType() {
        return new ClassifierType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LogType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.xes-standard.org/", name = "log")
    public JAXBElement<LogType> createLog(LogType value) {
        return new JAXBElement<LogType>(_Log_QNAME, LogType.class, null, value);
    }

}
