//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.01 at 04:10:21 PM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.xes-standard.org/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package es.uc3m.softlab.cbi4api.basu.xes.event.publisher.xsd.xes;
