//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.09 at 02:10:13 PM IST 
//


package es.uc3m.softlab.cbi4api.basu.mxml.event.publisher.xsd.mxml;

import java.io.Serializable;
import java.util.Calendar;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import es.uc3m.softlab.cbi4api.basu.mxml.event.publisher.xsd.TimeStampAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Data" minOccurs="0"/>
 *         &lt;element name="WorkflowModelElement" type="{http://www.w3.org/2001/XMLSchema}normalizedString"/>
 *         &lt;element name="EventType">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;>eventtypes">
 *                 &lt;attribute name="unknowntype" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Timestamp" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>dateTime">
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Originator" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "data",
    "workflowModelElement",
    "eventType",
    "timestamp",
    "originator"
})
@XmlRootElement(name = "AuditTrailEntry")
public class AuditTrailEntry
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "Data")
    protected Data data;
    @XmlElement(name = "WorkflowModelElement", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String workflowModelElement;
    @XmlElement(name = "EventType", required = true)
    protected AuditTrailEntry.EventType eventType;
    @XmlElement(name = "Timestamp")
    protected AuditTrailEntry.Timestamp timestamp;
    @XmlElement(name = "Originator")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String originator;

    /**
     * Gets the value of the data property.
     * 
     * @return
     *     possible object is
     *     {@link Data }
     *     
     */
    public Data getData() {
        return data;
    }

    /**
     * Sets the value of the data property.
     * 
     * @param value
     *     allowed object is
     *     {@link Data }
     *     
     */
    public void setData(Data value) {
        this.data = value;
    }

    public boolean isSetData() {
        return (this.data!= null);
    }

    /**
     * Gets the value of the workflowModelElement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWorkflowModelElement() {
        return workflowModelElement;
    }

    /**
     * Sets the value of the workflowModelElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWorkflowModelElement(String value) {
        this.workflowModelElement = value;
    }

    public boolean isSetWorkflowModelElement() {
        return (this.workflowModelElement!= null);
    }

    /**
     * Gets the value of the eventType property.
     * 
     * @return
     *     possible object is
     *     {@link AuditTrailEntry.EventType }
     *     
     */
    public AuditTrailEntry.EventType getEventType() {
        return eventType;
    }

    /**
     * Sets the value of the eventType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuditTrailEntry.EventType }
     *     
     */
    public void setEventType(AuditTrailEntry.EventType value) {
        this.eventType = value;
    }

    public boolean isSetEventType() {
        return (this.eventType!= null);
    }

    /**
     * Gets the value of the timestamp property.
     * 
     * @return
     *     possible object is
     *     {@link AuditTrailEntry.Timestamp }
     *     
     */
    public AuditTrailEntry.Timestamp getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuditTrailEntry.Timestamp }
     *     
     */
    public void setTimestamp(AuditTrailEntry.Timestamp value) {
        this.timestamp = value;
    }

    public boolean isSetTimestamp() {
        return (this.timestamp!= null);
    }

    /**
     * Gets the value of the originator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginator() {
        return originator;
    }

    /**
     * Sets the value of the originator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginator(String value) {
        this.originator = value;
    }

    public boolean isSetOriginator() {
        return (this.originator!= null);
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;>eventtypes">
     *       &lt;attribute name="unknowntype" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class EventType
        implements Serializable
    {

        private final static long serialVersionUID = 1L;
        @XmlValue
        protected Eventtypes value;
        @XmlAttribute
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        @XmlSchemaType(name = "normalizedString")
        protected String unknowntype;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link Eventtypes }
         *     
         */
        public Eventtypes getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link Eventtypes }
         *     
         */
        public void setValue(Eventtypes value) {
            this.value = value;
        }

        public boolean isSetValue() {
            return (this.value!= null);
        }

        /**
         * Gets the value of the unknowntype property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUnknowntype() {
            return unknowntype;
        }

        /**
         * Sets the value of the unknowntype property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUnknowntype(String value) {
            this.unknowntype = value;
        }

        public boolean isSetUnknowntype() {
            return (this.unknowntype!= null);
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>dateTime">
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Timestamp
        implements Serializable
    {

        private final static long serialVersionUID = 1L;
        @XmlValue
        @XmlJavaTypeAdapter(TimeStampAdapter.class)
        @XmlSchemaType(name = "dateTime")
        protected Calendar value;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public Calendar getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(Calendar value) {
            this.value = value;
        }

        public boolean isSetValue() {
            return (this.value!= null);
        }

    }

}
