//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.09 at 02:10:13 PM IST 
//


package es.uc3m.softlab.cbi4api.basu.mxml.event.publisher.xsd.mxml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for eventtypes.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="eventtypes">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString">
 *     &lt;enumeration value="schedule"/>
 *     &lt;enumeration value="assign"/>
 *     &lt;enumeration value="withdraw"/>
 *     &lt;enumeration value="reassign"/>
 *     &lt;enumeration value="start"/>
 *     &lt;enumeration value="suspend"/>
 *     &lt;enumeration value="resume"/>
 *     &lt;enumeration value="pi_abort"/>
 *     &lt;enumeration value="ate_abort"/>
 *     &lt;enumeration value="complete"/>
 *     &lt;enumeration value="autoskip"/>
 *     &lt;enumeration value="manualskip"/>
 *     &lt;enumeration value="unknown"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "eventtypes")
@XmlEnum
public enum Eventtypes {

    @XmlEnumValue("schedule")
    SCHEDULE("schedule"),
    @XmlEnumValue("assign")
    ASSIGN("assign"),
    @XmlEnumValue("withdraw")
    WITHDRAW("withdraw"),
    @XmlEnumValue("reassign")
    REASSIGN("reassign"),
    @XmlEnumValue("start")
    START("start"),
    @XmlEnumValue("suspend")
    SUSPEND("suspend"),
    @XmlEnumValue("resume")
    RESUME("resume"),
    @XmlEnumValue("pi_abort")
    PI_ABORT("pi_abort"),
    @XmlEnumValue("ate_abort")
    ATE_ABORT("ate_abort"),
    @XmlEnumValue("complete")
    COMPLETE("complete"),
    @XmlEnumValue("autoskip")
    AUTOSKIP("autoskip"),
    @XmlEnumValue("manualskip")
    MANUALSKIP("manualskip"),
    @XmlEnumValue("unknown")
    UNKNOWN("unknown");
    private final String value;

    Eventtypes(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Eventtypes fromValue(String v) {
        for (Eventtypes c: Eventtypes.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
