//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.09 at 02:10:13 PM IST 
//


package es.uc3m.softlab.cbi4api.basu.mxml.event.publisher.xsd.mxml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the es.uc3m.softlab.cbi4api.basu.mxml.event.publisher.xsd.mxml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: es.uc3m.softlab.cbi4api.basu.mxml.event.publisher.xsd.mxml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Source }
     * 
     */
    public Source createSource() {
        return new Source();
    }

    /**
     * Create an instance of {@link WorkflowLog }
     * 
     */
    public WorkflowLog createWorkflowLog() {
        return new WorkflowLog();
    }

    /**
     * Create an instance of {@link AuditTrailEntry.EventType }
     * 
     */
    public AuditTrailEntry.EventType createAuditTrailEntryEventType() {
        return new AuditTrailEntry.EventType();
    }

    /**
     * Create an instance of {@link AuditTrailEntry }
     * 
     */
    public AuditTrailEntry createAuditTrailEntry() {
        return new AuditTrailEntry();
    }

    /**
     * Create an instance of {@link AuditTrailEntry.Timestamp }
     * 
     */
    public AuditTrailEntry.Timestamp createAuditTrailEntryTimestamp() {
        return new AuditTrailEntry.Timestamp();
    }

    /**
     * Create an instance of {@link Data.Attribute }
     * 
     */
    public Data.Attribute createDataAttribute() {
        return new Data.Attribute();
    }

    /**
     * Create an instance of {@link ProcessInstance }
     * 
     */
    public ProcessInstance createProcessInstance() {
        return new ProcessInstance();
    }

    /**
     * Create an instance of {@link Process }
     * 
     */
    public Process createProcess() {
        return new Process();
    }

    /**
     * Create an instance of {@link Data }
     * 
     */
    public Data createData() {
        return new Data();
    }

}
