//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.01 at 04:10:21 PM BST 
//


package es.uc3m.softlab.cbi4api.basu.xes.event.publisher.xsd.xes.map;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the es.uc3m.softlab.cbi4api.basu.xes.event.publisher.xsd.xes.map package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: es.uc3m.softlab.cbi4api.basu.xes.event.publisher.xsd.xes.map
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link XesMap }
     * 
     */
    public XesMap createXesMap() {
        return new XesMap();
    }

    /**
     * Create an instance of {@link Event }
     * 
     */
    public Event createEvent() {
        return new Event();
    }

    /**
     * Create an instance of {@link Trace }
     * 
     */
    public Trace createTrace() {
        return new Trace();
    }

    /**
     * Create an instance of {@link StateTransitions }
     * 
     */
    public StateTransitions createStateTransitions() {
        return new StateTransitions();
    }

    /**
     * Create an instance of {@link StateTransitions.State }
     * 
     */
    public StateTransitions.State createStateTransitionsState() {
        return new StateTransitions.State();
    }

}
