//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.14 at 04:10:29 PM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.uc3m.es/softlab/basu/xesmap")
package es.uc3m.softlab.cbi4api.basu.xes.event.publisher.xsd.xes.map;
