//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.14 at 04:16:29 PM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.uc3m.es/softlab/gbas/response")
package es.uc3m.softlab.cbi4api.basu.event.subscriber.xsd.gbas.response;
