//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.14 at 04:10:29 PM BST 
//


package es.uc3m.softlab.cbi4api.basu.xes.event.publisher.xsd.xes.ext;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the es.uc3m.softlab.cbi4api.basu.xes.event.publisher.xsd.xes.ext package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _EventInt_QNAME = new QName("", "int");
    private final static QName _EventString_QNAME = new QName("", "string");
    private final static QName _EventBoolean_QNAME = new QName("", "boolean");
    private final static QName _EventDate_QNAME = new QName("", "date");
    private final static QName _EventFloat_QNAME = new QName("", "float");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: es.uc3m.softlab.cbi4api.basu.xes.event.publisher.xsd.xes.ext
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Event }
     * 
     */
    public Event createEvent() {
        return new Event();
    }

    /**
     * Create an instance of {@link Meta }
     * 
     */
    public Meta createMeta() {
        return new Meta();
    }

    /**
     * Create an instance of {@link Trace }
     * 
     */
    public Trace createTrace() {
        return new Trace();
    }

    /**
     * Create an instance of {@link Log }
     * 
     */
    public Log createLog() {
        return new Log();
    }

    /**
     * Create an instance of {@link AliasType }
     * 
     */
    public AliasType createAliasType() {
        return new AliasType();
    }

    /**
     * Create an instance of {@link AttributeType }
     * 
     */
    public AttributeType createAttributeType() {
        return new AttributeType();
    }

    /**
     * Create an instance of {@link Xesextension }
     * 
     */
    public Xesextension createXesextension() {
        return new Xesextension();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "int", scope = Event.class)
    public JAXBElement<AttributeType> createEventInt(AttributeType value) {
        return new JAXBElement<AttributeType>(_EventInt_QNAME, AttributeType.class, Event.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "string", scope = Event.class)
    public JAXBElement<AttributeType> createEventString(AttributeType value) {
        return new JAXBElement<AttributeType>(_EventString_QNAME, AttributeType.class, Event.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "boolean", scope = Event.class)
    public JAXBElement<AttributeType> createEventBoolean(AttributeType value) {
        return new JAXBElement<AttributeType>(_EventBoolean_QNAME, AttributeType.class, Event.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "date", scope = Event.class)
    public JAXBElement<AttributeType> createEventDate(AttributeType value) {
        return new JAXBElement<AttributeType>(_EventDate_QNAME, AttributeType.class, Event.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "float", scope = Event.class)
    public JAXBElement<AttributeType> createEventFloat(AttributeType value) {
        return new JAXBElement<AttributeType>(_EventFloat_QNAME, AttributeType.class, Event.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "int", scope = Meta.class)
    public JAXBElement<AttributeType> createMetaInt(AttributeType value) {
        return new JAXBElement<AttributeType>(_EventInt_QNAME, AttributeType.class, Meta.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "string", scope = Meta.class)
    public JAXBElement<AttributeType> createMetaString(AttributeType value) {
        return new JAXBElement<AttributeType>(_EventString_QNAME, AttributeType.class, Meta.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "boolean", scope = Meta.class)
    public JAXBElement<AttributeType> createMetaBoolean(AttributeType value) {
        return new JAXBElement<AttributeType>(_EventBoolean_QNAME, AttributeType.class, Meta.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "date", scope = Meta.class)
    public JAXBElement<AttributeType> createMetaDate(AttributeType value) {
        return new JAXBElement<AttributeType>(_EventDate_QNAME, AttributeType.class, Meta.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "float", scope = Meta.class)
    public JAXBElement<AttributeType> createMetaFloat(AttributeType value) {
        return new JAXBElement<AttributeType>(_EventFloat_QNAME, AttributeType.class, Meta.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "int", scope = Log.class)
    public JAXBElement<AttributeType> createLogInt(AttributeType value) {
        return new JAXBElement<AttributeType>(_EventInt_QNAME, AttributeType.class, Log.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "string", scope = Log.class)
    public JAXBElement<AttributeType> createLogString(AttributeType value) {
        return new JAXBElement<AttributeType>(_EventString_QNAME, AttributeType.class, Log.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "boolean", scope = Log.class)
    public JAXBElement<AttributeType> createLogBoolean(AttributeType value) {
        return new JAXBElement<AttributeType>(_EventBoolean_QNAME, AttributeType.class, Log.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "date", scope = Log.class)
    public JAXBElement<AttributeType> createLogDate(AttributeType value) {
        return new JAXBElement<AttributeType>(_EventDate_QNAME, AttributeType.class, Log.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "float", scope = Log.class)
    public JAXBElement<AttributeType> createLogFloat(AttributeType value) {
        return new JAXBElement<AttributeType>(_EventFloat_QNAME, AttributeType.class, Log.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "int", scope = Trace.class)
    public JAXBElement<AttributeType> createTraceInt(AttributeType value) {
        return new JAXBElement<AttributeType>(_EventInt_QNAME, AttributeType.class, Trace.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "string", scope = Trace.class)
    public JAXBElement<AttributeType> createTraceString(AttributeType value) {
        return new JAXBElement<AttributeType>(_EventString_QNAME, AttributeType.class, Trace.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "boolean", scope = Trace.class)
    public JAXBElement<AttributeType> createTraceBoolean(AttributeType value) {
        return new JAXBElement<AttributeType>(_EventBoolean_QNAME, AttributeType.class, Trace.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "date", scope = Trace.class)
    public JAXBElement<AttributeType> createTraceDate(AttributeType value) {
        return new JAXBElement<AttributeType>(_EventDate_QNAME, AttributeType.class, Trace.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "float", scope = Trace.class)
    public JAXBElement<AttributeType> createTraceFloat(AttributeType value) {
        return new JAXBElement<AttributeType>(_EventFloat_QNAME, AttributeType.class, Trace.class, value);
    }

}
